# Review and example assessment questions

# Question 5

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

## Pandas and data manipulation

1. Create a dataframe for this data:

    Animal   | Height | Weight
    Cat      | 30     | 5
    Dog      | 45     | 20
    Elephant | 200    | 4000
    Monkey   | 60     | 5
    Tiger    | 100    | 250

2. Sort it by Weight and print the names of the animals in Weight order.

3. Remove the row containing Elephant.

4. Split Monkey and Tiger into a separate dataframe.

5. Join the two remaining dataframes back together.

In [ ]:
# Answer goes here

In [ ]:
# Answer goes here